#!/usr/bin/env python3
"""Generate browsable HTML catalogs for a directory of game-asset packs.

Each immediate subdirectory of ROOT is treated as one "pack" and gets its own
page; an index.html links them all. Pages reference the original image files by
relative path, so they are only useful sitting in ROOT -- that is deliberate.

Prose written into _catalog_notes.json (next to the pages) is baked into the
generated HTML and survives regeneration.
"""

import argparse
import fnmatch
import html
import json
import os
import sys
from collections import defaultdict
from urllib.parse import quote

try:
    from PIL import Image, ImageDraw
except ImportError:
    sys.exit("Pillow is required: pip install Pillow")

IMAGE_EXT = {".png", ".jpg", ".jpeg", ".gif", ".bmp", ".webp"}
ARCHIVE_EXT = {".zip", ".7z", ".rar", ".unitypackage", ".tar", ".gz"}
JUNK_DIRS = {"__MACOSX", ".git", ".svn"}
JUNK_FILES = {".DS_Store", "Thumbs.db", "desktop.ini"}
NOTES_FILE = "_catalog_notes.json"
# stamped into every generated page so --prune only ever removes our own output
MARKER = "<!-- generated by asset-reviewer -->"
# sprites at or under this on their long edge are upscaled with nearest-neighbour
# rather than shown at native size. 64 keeps true pixel art in and 128px icons out.
PIXEL_MAX = 64


# --------------------------------------------------------------------------
# scanning
# --------------------------------------------------------------------------

class Asset:
    __slots__ = ("rel", "abs", "bytes", "w", "h", "variants")

    def __init__(self, rel, abs_, bytes_, w, h):
        self.rel = rel
        self.abs = abs_
        self.bytes = bytes_
        self.w = w
        self.h = h
        self.variants = []   # other Assets collapsed into this one

    @property
    def name(self):
        return os.path.basename(self.rel)

    @property
    def group(self):
        d = os.path.dirname(self.rel)
        return d if d else "(root)"

    @property
    def pixels(self):
        return (self.w or 0) * (self.h or 0)


def scan_pack(pack_dir, exclude=()):
    """Walk one pack. Returns (images, archives, other_count, excluded_count).

    `exclude` holds fnmatch patterns tested against each directory's path
    relative to the pack -- useful for pruning duplicated engine projects.
    """
    images, archives, other, dropped = [], [], 0, 0
    for root, dirs, files in os.walk(pack_dir):
        keep = []
        for d in sorted(dirs):
            if d in JUNK_DIRS:
                continue
            drel = os.path.relpath(os.path.join(root, d), pack_dir).replace("\\", "/")
            if any(fnmatch.fnmatch(drel, p) or fnmatch.fnmatch(d, p) for p in exclude):
                dropped += sum(len(fs) for _, _, fs in os.walk(os.path.join(root, d)))
                continue
            keep.append(d)
        dirs[:] = keep
        for fn in sorted(files):
            if fn in JUNK_FILES or fn.startswith("._"):
                continue
            path = os.path.join(root, fn)
            rel = os.path.relpath(path, pack_dir).replace("\\", "/")
            ext = os.path.splitext(fn)[1].lower()
            if ext in IMAGE_EXT:
                try:
                    with Image.open(path) as im:
                        w, h = im.size
                except Exception:
                    w = h = None
                images.append(Asset(rel, path, os.path.getsize(path), w, h))
            elif ext in ARCHIVE_EXT:
                archives.append((rel, os.path.getsize(path)))
            else:
                other += 1
    return images, archives, other, dropped


def collapse_resolution_variants(images):
    """Fold `.../128/foo.png` and `.../512/foo.png` into one card.

    Keys on the relative path with any purely-numeric directory component
    removed, so resolution folders merge but sibling style folders
    (Round/ vs Square/) stay distinct. Largest pixel count wins as primary.
    """
    buckets = defaultdict(list)
    for a in images:
        parts = [p for p in a.rel.split("/") if not p.isdigit()]
        buckets["/".join(parts)].append(a)

    primaries = []
    for group in buckets.values():
        group.sort(key=lambda a: a.pixels, reverse=True)
        primary = group[0]
        primary.variants = group[1:]
        primaries.append(primary)
    primaries.sort(key=lambda a: a.rel)
    return primaries


# --------------------------------------------------------------------------
# contact sheets (for model review, not for the pages)
# --------------------------------------------------------------------------

def build_sheets(pack_name, assets, out_dir, tile=128, cols=8, rows=8):
    """Tile a representative sample into 1024x1024 PNGs. Returns (paths, legend)."""
    per_sheet = cols * rows
    if not assets:
        return [], []

    # spread the sample evenly across the pack rather than taking a prefix
    cap = per_sheet * 4
    if len(assets) > cap:
        step = len(assets) / cap
        sample = [assets[int(i * step)] for i in range(cap)]
    else:
        sample = list(assets)

    os.makedirs(out_dir, exist_ok=True)
    paths, legend = [], []
    for s_idx in range(0, len(sample), per_sheet):
        chunk = sample[s_idx:s_idx + per_sheet]
        sheet = Image.new("RGB", (cols * tile, rows * tile), (107, 107, 107))
        draw = ImageDraw.Draw(sheet)
        for i, a in enumerate(chunk):
            n = s_idx + i + 1
            legend.append((n, a.rel, "%sx%s" % (a.w, a.h)))
            x, y = (i % cols) * tile, (i // cols) * tile
            try:
                with Image.open(a.abs) as im:
                    im = im.convert("RGBA")
                    im.thumbnail((tile - 12, tile - 12), Image.LANCZOS)
                    sheet.paste(im, (x + (tile - im.width) // 2,
                                     y + (tile - im.height) // 2), im)
            except Exception:
                draw.text((x + 6, y + tile // 2), "err", fill=(255, 80, 80))
            draw.rectangle([x, y, x + tile - 1, y + tile - 1], outline=(60, 60, 60))
            draw.text((x + 3, y + 2), str(n), fill=(255, 255, 0))
        p = os.path.join(out_dir, "%s_sheet%d.png" % (pack_name, s_idx // per_sheet + 1))
        sheet.save(p)
        paths.append(p)
    return paths, legend


# --------------------------------------------------------------------------
# rendering
# --------------------------------------------------------------------------

CSS = """
:root{--bg:#f6f6f4;--panel:#fff;--ink:#1c1c1a;--muted:#6a6a66;--line:#dedcd6;
--accent:#7a5c2e;--tile:#e9e7e1;--chip:#efece4}
@media (prefers-color-scheme:dark){:root{--bg:#16161a;--panel:#1e1e23;--ink:#e9e7e1;
--muted:#9a978f;--line:#33333a;--accent:#d7b877;--tile:#26262c;--chip:#2c2c33}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
font:15px/1.55 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}
a{color:var(--accent)}
header{position:sticky;top:0;z-index:5;background:var(--panel);
border-bottom:1px solid var(--line);padding:14px 22px}
h1{margin:0 0 3px;font-size:19px;letter-spacing:-.01em}
h2{margin:34px 0 10px;font-size:15px;font-family:ui-monospace,Consolas,monospace;
color:var(--accent);border-bottom:1px solid var(--line);padding-bottom:6px}
.sub{color:var(--muted);font-size:13px}
main{padding:22px;max-width:1500px;margin:0 auto}
.notes{background:var(--panel);border:1px solid var(--line);border-left:3px solid var(--accent);
padding:14px 18px;margin:18px 0;border-radius:4px}
.notes p{margin:0 0 8px}.notes p:last-child{margin:0}
.notes ul{margin:8px 0 0;padding-left:20px}
.stats{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}
.chip{background:var(--chip);border:1px solid var(--line);border-radius:99px;
padding:2px 11px;font-size:12px;color:var(--muted)}
.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:14px}
.card{background:var(--panel);border:1px solid var(--line);border-radius:6px;
padding:9px;display:flex;flex-direction:column;gap:7px}
.thumb{background:var(--tile);border-radius:4px;height:170px;display:flex;
align-items:center;justify-content:center;overflow:hidden}
.thumb img{max-width:100%;max-height:170px;object-fit:contain}
/* tiny sprites would otherwise render at their native 32px inside a 170px box.
   Blow them up to fill it, nearest-neighbour so pixel art stays crisp. */
.thumb img.px{width:100%;height:170px;max-height:170px;object-fit:contain;
image-rendering:pixelated;image-rendering:crisp-edges}
.fn{font-size:12px;font-weight:600;word-break:break-all;line-height:1.35}
.meta{font-size:11px;color:var(--muted);font-family:ui-monospace,Consolas,monospace}
.path{font-size:10.5px;color:var(--muted);font-family:ui-monospace,Consolas,monospace;
word-break:break-all;background:var(--tile);padding:4px 6px;border-radius:3px;
cursor:pointer;border:1px solid transparent}
.path:hover{border-color:var(--accent)}
.path.copied{border-color:var(--accent);color:var(--accent)}
table{border-collapse:collapse;width:100%;font-size:13px}
th,td{text-align:left;padding:7px 12px;border-bottom:1px solid var(--line)}
th{color:var(--muted);font-weight:600;font-size:12px}
td.num{text-align:right;font-family:ui-monospace,Consolas,monospace}
.empty{color:var(--muted);font-style:italic;padding:20px 0}
.wrap{overflow-x:auto}
"""

COPY_JS = """
document.addEventListener('click',function(e){
  var el=e.target.closest('.path'); if(!el) return;
  var t=el.dataset.full||el.textContent;
  var done=function(){el.classList.add('copied');
    setTimeout(function(){el.classList.remove('copied')},900)};
  if(navigator.clipboard&&window.isSecureContext){
    navigator.clipboard.writeText(t).then(done)
  } else {
    var ta=document.createElement('textarea');ta.value=t;document.body.appendChild(ta);
    ta.select();try{document.execCommand('copy')}catch(_){}
    document.body.removeChild(ta);done()
  }
});
"""


def esc(s):
    return html.escape(str(s), quote=True)


def url(rel):
    """Relative path -> attribute-safe URL. Spaces are legal in a src but
    '#' and '%' are not, and asset packs do ship both."""
    return esc(quote(rel, safe="/"))


def human(n):
    for unit in ("B", "KB", "MB", "GB"):
        if n < 1024 or unit == "GB":
            return "%d B" % n if unit == "B" else "%.1f %s" % (n, unit)
        n /= 1024.0


def page(title, body):
    return (MARKER + "<!doctype html><html lang=en><meta charset=utf-8>"
            "<meta name=viewport content='width=device-width,initial-scale=1'>"
            "<title>%s</title><style>%s</style>%s<script>%s</script></html>"
            % (esc(title), CSS, body, COPY_JS))


def render_notes(note):
    if not note:
        return ""
    out = ["<div class=notes>"]
    summary = note.get("summary")
    if summary:
        for para in summary.split("\n\n"):
            out.append("<p>%s</p>" % esc(para))
    highlights = note.get("highlights") or []
    if highlights:
        out.append("<ul>%s</ul>" % "".join("<li>%s</li>" % esc(h) for h in highlights))
    out.append("</div>")
    return "".join(out)


def ensure_preview(asset, pack, out, limit, max_edge=1024):
    """Huge sprite sheets cannot be inlined at full size -- a 2048x8192 PNG is
    ~67 MB decoded, and a page of them will hang the browser. For those only,
    write a downscaled copy next to the pages and point the card at it.

    Returns a path relative to `out`, or None to inline the original.
    """
    if not asset.pixels or asset.pixels <= limit:
        return None
    rel = os.path.join("_previews", pack, asset.rel.replace("/", os.sep))
    rel = os.path.splitext(rel)[0] + ".png"
    dst = os.path.join(out, rel)
    if not os.path.exists(dst) or os.path.getmtime(dst) < os.path.getmtime(asset.abs):
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        try:
            with Image.open(asset.abs) as im:
                im = im.convert("RGBA")
                im.thumbnail((max_edge, max_edge), Image.LANCZOS)
                im.save(dst)
        except Exception:
            return None
    return rel.replace(os.sep, "/")


def render_pack(pack, root, images, archives, other, note, collapsed, dropped=0,
                out=None, inline_limit=0):
    total_bytes = sum(a.bytes for a in images)
    dims = defaultdict(int)
    for a in images:
        if a.w:
            dims[(a.w, a.h)] += 1
    top = sorted(dims.items(), key=lambda kv: -kv[1])[:4]
    top_dims = ", ".join("%dx%d" % wh for wh, _ in top) or "-"
    folded = sum(len(a.variants) for a in collapsed)

    chips = ["%d assets" % len(collapsed), "%d files" % len(images),
             human(total_bytes), "sizes: " + top_dims]
    if folded:
        chips.append("%d resolution variants folded in" % folded)
    if archives:
        chips.append("%d archives" % len(archives))
    if other:
        chips.append("%d other files" % other)
    if dropped:
        chips.append("%d files excluded" % dropped)

    pack_abs = os.path.join(root, pack)
    body = ["<header><h1>%s</h1>" % esc(pack),
            "<div class=sub><a href='index.html'>&larr; all packs</a> &middot; "
            "<span class=path data-full='%s'>%s</span></div>" % (esc(pack_abs), esc(pack_abs)),
            "<div class=stats>%s</div></header><main>"
            % "".join("<span class=chip>%s</span>" % esc(c) for c in chips),
            render_notes(note)]

    if not images:
        body.append("<p class=empty>No browsable images in this pack.</p>")

    by_group = defaultdict(list)
    for a in collapsed:
        by_group[a.group].append(a)

    for grp in sorted(by_group):
        items = by_group[grp]
        body.append("<h2>%s <span class=sub>(%d)</span></h2><div class=grid>"
                    % (esc(grp), len(items)))
        for a in items:
            src = url("%s/%s" % (pack, a.rel))
            dim = "%dx%d" % (a.w, a.h) if a.w else "?"
            if a.variants:
                widths = sorted({v.w for v in a.variants if v.w} | {a.w or 0}, reverse=True)
                dim += " &middot; also " + "/".join(str(s) for s in widths[1:])
            full = os.path.join(root, pack, a.rel.replace("/", os.sep))
            shown = src
            cls = ""
            if inline_limit and out:
                prev = ensure_preview(a, pack, out, inline_limit)
                if prev:
                    shown = url(prev)
                    dim += " &middot; <b>preview</b>"
            if a.w and max(a.w, a.h) <= PIXEL_MAX:
                cls = " class=px"
            body.append(
                "<div class=card><div class=thumb>"
                "<a href='%s' target=_blank><img%s loading=lazy src='%s' alt=''></a></div>"
                "<div class=fn>%s</div><div class=meta>%s &middot; %s</div>"
                "<div class=path data-full='%s' title='click to copy full path'>%s</div></div>"
                % (src, cls, shown, esc(a.name), dim, esc(human(a.bytes)),
                   esc(full), esc(a.rel)))
        body.append("</div>")

    if archives:
        body.append("<h2>archives (not expanded)</h2><div class=wrap><table>"
                    "<tr><th>file</th><th>size</th></tr>")
        for rel, size in archives:
            full = os.path.join(root, pack, rel.replace("/", os.sep))
            body.append("<tr><td><span class=path data-full='%s'>%s</span></td>"
                        "<td class=num>%s</td></tr>" % (esc(full), esc(rel), esc(human(size))))
        body.append("</table></div>")

    body.append("</main>")
    return page("%s - asset catalog" % pack, "".join(body))


def render_index(root, rows, note):
    body = ["<header><h1>Asset catalog</h1><div class=sub>"
            "<span class=path data-full='%s'>%s</span> &middot; %d packs</div></header><main>"
            % (esc(root), esc(root), len(rows)),
            render_notes(note),
            "<div class=wrap><table><tr><th>pack</th><th>assets</th><th>files</th>"
            "<th>size</th><th>notes</th></tr>"]
    for r in rows:
        link = ("<a href='%s'>%s</a>" % (url(r["page"]), esc(r["pack"]))
                if r["page"] else esc(r["pack"]))
        body.append("<tr><td>%s</td><td class=num>%d</td><td class=num>%d</td>"
                    "<td class=num>%s</td><td class=sub>%s</td></tr>"
                    % (link, r["assets"], r["files"], esc(human(r["bytes"])), esc(r["blurb"])))
    body.append("</table></div></main>")
    return page("Asset catalog", "".join(body))


# --------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description="Build HTML catalogs for asset packs.")
    ap.add_argument("root", help="directory whose immediate subdirectories are packs")
    ap.add_argument("--out", help="where to write the HTML (default: ROOT)")
    ap.add_argument("--pack", action="append", help="limit to this pack (repeatable)")
    ap.add_argument("--sheets-dir", help="also build contact sheets here, for model review")
    ap.add_argument("--no-collapse", action="store_true",
                    help="do not fold numeric resolution folders into one card")
    ap.add_argument("--exclude", action="append", default=[], metavar="GLOB",
                    help="skip directories matching this glob (repeatable), e.g. "
                         "'*-mainV2' to drop duplicated per-engine project copies")
    ap.add_argument("--prune", action="store_true",
                    help="delete previously generated pages whose pack is gone")
    ap.add_argument("--inline-limit", type=int, default=4_000_000, metavar="PIXELS",
                    help="images larger than this get a downscaled preview in "
                         "_previews/ instead of being inlined at full size "
                         "(default 4000000; 0 disables)")
    args = ap.parse_args()

    root = os.path.abspath(args.root)
    out = os.path.abspath(args.out) if args.out else root
    if not os.path.isdir(root):
        sys.exit("not a directory: %s" % root)
    os.makedirs(out, exist_ok=True)

    notes = {}
    npath = os.path.join(out, NOTES_FILE)
    if os.path.exists(npath):
        with open(npath, encoding="utf-8") as fh:
            notes = json.load(fh)
    pack_notes = notes.get("packs", {})

    packs = sorted(d for d in os.listdir(root)
                   if os.path.isdir(os.path.join(root, d))
                   and d not in JUNK_DIRS and not d.startswith("_"))
    if args.pack:
        wanted = set(args.pack)
        packs = [p for p in packs if p in wanted]
        missing = wanted - set(packs)
        if missing:
            sys.exit("no such pack(s): %s" % ", ".join(sorted(missing)))
    if not packs:
        sys.exit("no pack directories found under %s" % root)

    rows = []
    generated = {"index.html"}
    for pack in packs:
        images, archives, other, dropped = scan_pack(os.path.join(root, pack),
                                                     args.exclude)
        collapsed = images if args.no_collapse else collapse_resolution_variants(images)
        note = pack_notes.get(pack)

        pagename = "%s.html" % pack
        generated.add(pagename)
        with open(os.path.join(out, pagename), "w", encoding="utf-8") as fh:
            fh.write(render_pack(pack, root, images, archives, other, note,
                                 collapsed, dropped, out, args.inline_limit))

        rows.append({"pack": pack, "page": pagename, "assets": len(collapsed),
                     "files": len(images), "bytes": sum(a.bytes for a in images),
                     "blurb": (note or {}).get("blurb", "")})

        extra = " / %d archives" % len(archives) if archives else ""
        extra += " / %d excluded" % dropped if dropped else ""
        print("%s: %d assets / %d files%s -> %s"
              % (pack, len(collapsed), len(images), extra, pagename))

        if args.sheets_dir and collapsed:
            paths, legend = build_sheets(pack, collapsed, os.path.abspath(args.sheets_dir))
            for p in paths:
                print("    sheet: %s" % p)
            for n, rel, dim in legend:
                print("    [%d] %s (%s)" % (n, rel, dim))

    with open(os.path.join(out, "index.html"), "w", encoding="utf-8") as fh:
        fh.write(render_index(root, rows, notes.get("index")))

    # pages whose pack directory has since been deleted. Only ever touch files
    # carrying our own marker, so a hand-written .html in ROOT is never at risk.
    stale = []
    for fn in sorted(os.listdir(out)):
        if not fn.endswith(".html") or fn in generated:
            continue
        p = os.path.join(out, fn)
        try:
            with open(p, encoding="utf-8") as fh:
                if not fh.read(len(MARKER)).startswith(MARKER):
                    continue
        except OSError:
            continue
        stale.append(fn)
        if args.prune:
            os.remove(p)
    if stale:
        verb = "removed stale page" if args.prune else "stale page (use --prune)"
        for fn in stale:
            print("%s: %s" % (verb, fn))

    print("\nindex -> %s" % os.path.join(out, "index.html"))
    if not os.path.exists(npath):
        print("notes  -> write %s to bake prose into these pages" % npath)


if __name__ == "__main__":
    main()
