#!/usr/bin/env python3
"""Show how a pack's art actually moves in a game.

Two cases, because asset packs come in two shapes:

  * **One pose per subject, no frames.** Nothing is missing -- the sprite is
    meant to be moved rather than redrawn. `transform_fragment` demonstrates
    that with CSS transforms, a filter and opacity, on the unmodified file.
  * **Real frame sequences.** `find_sequences` spots folders of numbered frames
    and `sequence_fragment` builds a player for them, so an eight-frame
    explosion can be watched instead of read as eight near-identical cards.

catalog.py embeds these directly into the pack page they belong to. Running
this file on its own still produces a standalone page for one sprite:

    python motion.py <SPRITE.png> --out <DIR>
"""

import argparse
import html
import os
import posixpath
import re
import sys
from collections import Counter, defaultdict
from urllib.parse import quote

try:
    from PIL import Image
except ImportError:
    sys.exit("needs Pillow:  pip install pillow")

# must match catalog.py exactly -- --prune identifies its own output by this
MARKER = "<!-- generated by asset-reviewer -->"

PAGE_NAME = "sprite-motion.html"

# art at or under this on its long edge is the single-pose case: small enough
# that the game is expected to scale it up
DEMO_MAX_EDGE = 128


# Each entry is applied to the sprite AND printed under it, from this one
# string, so the code on screen is always the code running. "term" is the name
# other people use -- some are real terms of art, some are only descriptions,
# and the page says which.
DEMOS = [
    {
        "id": "static",
        "label": "static",
        "term": "the asset as shipped",
        "note": "The asset as shipped. This is the control -- everything else "
                "on this page is the same file.",
        "css": "",
    },
    {
        "id": "bob",
        "label": "idle bob",
        "term": "idle animation — “bob” is informal",
        "note": "Two or three source pixels of vertical travel. This one effect "
                "does most of the work of making a still image read as alive.",
        "css": """.a-bob{animation:bob 1.6s ease-in-out infinite}
@keyframes bob{
  0%,100%{transform:translateY(0)}
  50%    {transform:translateY(-9%)}
}""",
    },
    {
        "id": "breathe",
        "label": "breathe",
        "term": "squash and stretch — standard, Disney principle 1",
        "note": "Squash and stretch about the feet. transform-origin is bottom "
                "centre so the creature stays planted instead of floating.",
        "css": """.a-breathe{animation:breathe 2.2s ease-in-out infinite}
@keyframes breathe{
  0%,100%{transform:scale(1,1)}
  50%    {transform:scale(.96,1.04)}
}""",
    },
    {
        "id": "float",
        "label": "hover",
        "term": "float / hover idle",
        "note": "Bob plus a slow tilt. For anything airborne -- ghosts, "
                "eyeballs, wisps. Rotation on pixel art resamples the grid, so "
                "keep the angle small.",
        "css": """.a-float{animation:float 3s ease-in-out infinite}
@keyframes float{
  0%,100%{transform:translateY(0)   rotate(-2deg)}
  50%    {transform:translateY(-14%) rotate(2deg)}
}""",
    },
    {
        "id": "walk",
        "label": "fake walk",
        "term": "no standard name; procedural locomotion",
        "note": "The classic no-walk-cycle cheat: hop and tilt in step. Sells "
                "movement across a map without a single extra frame.",
        "css": """.a-walk{animation:walk .42s ease-in-out infinite}
@keyframes walk{
  0%,100%{transform:translateY(0)    rotate(-3deg)}
  50%    {transform:translateY(-11%) rotate(3deg)}
}""",
    },
    {
        "id": "lunge",
        "label": "attack lunge",
        "term": "anticipation → action → follow-through",
        "trigger": True,
        "note": "Wind back, snap forward, settle. Roughly 400ms total. This is "
                "an entire attack animation with no attack art.",
        "css": """.a-lunge{animation:lunge .4s cubic-bezier(.3,0,.2,1)}
@keyframes lunge{
  0%  {transform:translateX(0)    scale(1,1)}
  25% {transform:translateX(-12%) scale(1.06,.94)}
  45% {transform:translateX(34%)  scale(.92,1.08)}
  100%{transform:translateX(0)    scale(1,1)}
}""",
    },
    {
        "id": "hit",
        "label": "took a hit",
        "term": "hit reaction; hitstun is the stun window",
        "trigger": True,
        "note": "brightness(0) invert(1) flattens the sprite to a white "
                "silhouette while keeping its alpha, so the flash traces the "
                "artwork exactly. Add knockback and a screen shake.",
        "css": """.a-hit{animation:hit .3s steps(1,end) 3}
@keyframes hit{
  0%  {filter:brightness(0) invert(1); transform:translateX(9%)}
  50% {filter:none;                    transform:translateX(-4%)}
  100%{filter:none;                    transform:translateX(0)}
}""",
    },
    {
        "id": "death",
        "label": "death",
        "term": "death / dissolve",
        "trigger": True,
        "note": "Tip over, sink, fade. Pair it with a particle burst and the "
                "player never notices there was no death frame.",
        "css": """.a-death{animation:death .7s ease-in forwards}
@keyframes death{
  0%  {transform:rotate(0)     translateY(0);   opacity:1}
  30% {transform:rotate(-14deg) translateY(-8%); opacity:1}
  100%{transform:rotate(84deg)  translateY(30%); opacity:0}
}""",
    },
]

# the scripted sequence in the "assembled" panel
COMBAT_STEPS = [("bob", 1400), ("lunge", 500), ("bob", 700),
                ("hit", 950), ("bob", 1600)]


# --------------------------------------------------------------------------
# styles
#
# SECTION_CSS is embedded into pack pages by catalog.py, so everything is
# scoped under .usage and the two class names catalog.py already owns (.card,
# .grid) are spelled .ucard / .ugrid here to avoid colliding with them.
# --------------------------------------------------------------------------

SECTION_CSS = """
.usage{--scale:6}
.usage .stage{background:var(--tile);border-radius:4px;height:210px;display:flex;
align-items:flex-end;justify-content:center;overflow:hidden;position:relative}
.usage .stage:after{content:"";position:absolute;left:12%;right:12%;bottom:26px;
border-bottom:1px dashed var(--line)}
/* width is driven by scale, but never let a large source overflow its stage --
   pointing this at a 512px icon should letterbox, not spill */
.usage .sprite{width:calc(var(--w)*var(--scale)*1px);height:auto;margin-bottom:26px;
max-width:100%;max-height:calc(100% - 34px);object-fit:contain;
transform-origin:50% 100%;position:relative;
image-rendering:pixelated;image-rendering:crisp-edges}
.usage.smooth .sprite{image-rendering:auto}

.usage .ugrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(330px,1fr));
gap:16px}
.usage .ucard{background:var(--panel);border:1px solid var(--line);border-radius:6px;
padding:11px;display:flex;flex-direction:column;gap:9px}
.usage .ucard .stage{height:170px}
.usage .ucard .sprite{width:calc(var(--w)*var(--cardscale)*1px)}
.usage .hd{display:flex;align-items:center;justify-content:space-between;gap:8px}
.usage .hd b{font-size:13px}
/* the searchable industry term, so the panel labels don't strand you with
   vocabulary nobody else uses */
.usage .term{font:11px/1.4 ui-monospace,Consolas,monospace;color:var(--accent);
margin-top:-4px}
.usage .why{font-size:12px;color:var(--muted);margin:0}
/* wrap rather than scroll: the point of this is reading the CSS, and a clipped
   line in a narrow card is worse than a wrapped one */
.usage pre{margin:0;background:var(--tile);border:1px solid var(--line);
border-radius:4px;padding:9px 11px;font:11.5px/1.5 ui-monospace,Consolas,monospace;
white-space:pre-wrap;overflow-wrap:anywhere;color:var(--ink)}
.usage button{font:12px inherit;font-family:inherit;background:var(--chip);
color:var(--ink);border:1px solid var(--line);border-radius:4px;padding:3px 11px;
cursor:pointer}
.usage button:hover{border-color:var(--accent);color:var(--accent)}

.usage .controls{background:var(--panel);border:1px solid var(--line);
border-radius:6px;padding:14px 18px;display:flex;flex-wrap:wrap;gap:20px;
align-items:center;margin:16px 0}
.usage .controls label{font-size:13px;display:flex;align-items:center;gap:8px}
.usage .controls input[type=range]{width:190px}
.usage .val{font-family:ui-monospace,Consolas,monospace;font-size:12px;
color:var(--accent);min-width:52px;display:inline-block}
.usage .warn{color:var(--muted);font-size:12px;margin:8px 0 0}
.usage .side{display:grid;grid-template-columns:repeat(auto-fit,minmax(240px,1fr));
gap:16px}

/* ---- frame-sequence player -------------------------------------------- */
/* every frame is in the DOM and toggled by class, so playback never waits on
   a network fetch the way swapping src would */
.usage .fp .stage{height:200px;align-items:center}
.usage .fp .stage:after{content:none}   /* no ground line: frames are centred */
/* smooth by default -- these frames are usually being scaled DOWN to fit, and
   nearest-neighbour downsampling of non-pixel art just adds aliasing. Only
   genuinely small frames get the crisp treatment. */
.usage .fp .frame{position:absolute;max-width:94%;max-height:94%;
object-fit:contain;opacity:0}
.usage .fp .frame.px{image-rendering:pixelated;image-rendering:crisp-edges}
.usage .fp .frame.on{opacity:1}
.usage .fpctl{display:flex;align-items:center;gap:12px;flex-wrap:wrap;
font-size:12px;color:var(--muted)}
.usage .fpctl input[type=range]{width:120px}
.usage .fpctl select{font:12px inherit;font-family:inherit;background:var(--chip);
color:var(--ink);border:1px solid var(--line);border-radius:4px;padding:3px 6px;
max-width:170px}

/* ---- sprite-sheet player ----------------------------------------------- */
/* one cell of the sheet shown through a window; playback moves the background
   rather than swapping images, which is what an engine does too */
.usage .shstage{align-items:center}
.usage .shstage:after{content:none}
.usage .shview{background-repeat:no-repeat;background-position:0 0;
image-rendering:auto}
"""

# chrome for the standalone page only; catalog.py supplies its own
PAGE_CHROME = """
:root{--bg:#f6f6f4;--panel:#fff;--ink:#1c1c1a;--muted:#6a6a66;--line:#dedcd6;
--accent:#7a5c2e;--tile:#e9e7e1;--chip:#efece4}
@media (prefers-color-scheme:dark){:root{--bg:#16161a;--panel:#1e1e23;--ink:#e9e7e1;
--muted:#9a978f;--line:#33333a;--accent:#d7b877;--tile:#26262c;--chip:#2c2c33}}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--ink);
font:15px/1.55 ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif}
a{color:var(--accent)}
header{background:var(--panel);border-bottom:1px solid var(--line);padding:14px 22px}
h1{margin:0 0 3px;font-size:19px;letter-spacing:-.01em}
h2{margin:34px 0 10px;font-size:15px;font-family:ui-monospace,Consolas,monospace;
color:var(--accent);border-bottom:1px solid var(--line);padding-bottom:6px}
.sub{color:var(--muted);font-size:13px}
main{padding:22px;max-width:1500px;margin:0 auto}
.path{font-size:11px;color:var(--muted);font-family:ui-monospace,Consolas,monospace;
word-break:break-all;background:var(--tile);padding:4px 6px;border-radius:3px;
cursor:pointer;border:1px solid transparent;display:inline-block}
.path:hover{border-color:var(--accent)}
.path.copied{border-color:var(--accent);color:var(--accent)}
.notes{background:var(--panel);border:1px solid var(--line);
border-left:3px solid var(--accent);padding:14px 18px;margin:18px 0;border-radius:4px}
.notes p{margin:0 0 8px}.notes p:last-child{margin:0}
"""


SECTION_JS = """
(function(){
var u=document.querySelector('.usage'); if(!u) return;

/* ---- scale + filtering (single-pose demo only) ----------------------- */
var sc=document.getElementById('sc'), snap=document.getElementById('snap'),
    sm=document.getElementById('sm'), out=document.getElementById('scval');
if(sc){
  var apply=function(){
    var v=parseFloat(sc.value);
    if(snap.checked){v=Math.max(1,Math.round(v))}
    u.style.setProperty('--scale',v);
    out.textContent=v.toFixed(2).replace(/\\.00$/,'')+'x';
    u.classList.toggle('smooth',sm.checked);
    document.getElementById('nonint').hidden=snap.checked||v===Math.round(v);
  };
  [sc,snap,sm].forEach(function(el){el.addEventListener('input',apply)});
  apply();
}

/* ---- one-shot transform demos ---------------------------------------- */
function play(el,name){
  el.classList.remove('a-'+name);
  void el.offsetWidth;
  el.classList.add('a-'+name);
}
u.addEventListener('click',function(e){
  var b=e.target.closest('[data-play]'); if(!b) return;
  play(b.closest('.ucard').querySelector('.sprite'),b.dataset.play);
});
/* one-shots stop after running once, so clear the class when they end */
u.addEventListener('animationend',function(e){
  var el=e.target;
  if(el.dataset&&el.dataset.trigger&&el.dataset.anim!=='death'){
    el.classList.remove('a-'+el.dataset.anim);
  }
},true);

/* ---- assembled loop: idle -> attack -> idle -> take a hit -> idle ----- */
var STEPS=COMBAT_STEPS;
var loopImg=document.getElementById('loopsprite'),
    loopLbl=document.getElementById('looplbl'), li=0, timer=null;
if(loopImg){
  var step=function(){
    var s=STEPS[li%STEPS.length]; li++;
    loopImg.className='sprite';
    void loopImg.offsetWidth;
    loopImg.classList.add('a-'+s[0]);
    loopLbl.textContent=s[0];
    timer=setTimeout(step,s[1]);
  };
  document.getElementById('loopbtn').addEventListener('click',function(){
    if(timer){clearTimeout(timer);timer=null;loopImg.className='sprite';
      loopLbl.textContent='stopped';this.textContent='start'}
    else{li=0;step();this.textContent='stop'}
  });
}

/* ---- frame-sequence players ------------------------------------------ */
Array.prototype.forEach.call(u.querySelectorAll('.fp'),function(fp){
  var frames=fp.querySelectorAll('.frame'),
      btn=fp.querySelector('[data-fp]'),
      rng=fp.querySelector('.fps'),
      lbl=fp.querySelector('.fpsval'),
      pos=fp.querySelector('.fpnum'),
      i=0, t=null;
  var show=function(){
    Array.prototype.forEach.call(frames,function(f,n){
      f.classList.toggle('on',n===i)});
    pos.textContent=(i+1)+'/'+frames.length;
  };
  var tick=function(){
    i=(i+1)%frames.length; show();
    t=setTimeout(tick,1000/parseFloat(rng.value));
  };
  var start=function(){if(!t){t=setTimeout(tick,1000/parseFloat(rng.value));
    btn.textContent='pause'}};
  var stop=function(){if(t){clearTimeout(t);t=null;btn.textContent='play'}};
  btn.addEventListener('click',function(){t?stop():start()});
  rng.addEventListener('input',function(){
    lbl.textContent=rng.value+' fps'; if(t){stop();start()}});
  fp.querySelector('[data-step]').addEventListener('click',function(){
    stop(); i=(i+1)%frames.length; show()});
  show(); start();
});

/* ---- sprite-sheet players -------------------------------------------- */
Array.prototype.forEach.call(u.querySelectorAll('.sh'),function(sh){
  var cols=+sh.dataset.cols, cell=+sh.dataset.cell,
      view=sh.querySelector('.shview'),
      sel=sh.querySelector('.shrow'),
      btn=sh.querySelector('[data-fp]'),
      rng=sh.querySelector('.fps'),
      lbl=sh.querySelector('.fpsval'),
      pos=sh.querySelector('.fpnum'),
      i=0, t=null;
  var show=function(){
    view.style.backgroundPosition=(-i*cell)+'px '+(-sel.value*cell)+'px';
    pos.textContent=(i+1)+'/'+cols;
  };
  var tick=function(){i=(i+1)%cols; show();
    t=setTimeout(tick,1000/parseFloat(rng.value))};
  var start=function(){if(!t){t=setTimeout(tick,1000/parseFloat(rng.value));
    btn.textContent='pause'}};
  var stop=function(){if(t){clearTimeout(t);t=null;btn.textContent='play'}};
  btn.addEventListener('click',function(){t?stop():start()});
  rng.addEventListener('input',function(){
    lbl.textContent=rng.value+' fps'; if(t){stop();start()}});
  sel.addEventListener('change',function(){i=0; show()});
  sh.querySelector('[data-step]').addEventListener('click',function(){
    stop(); i=(i+1)%cols; show()});
  show(); start();
});
})();
"""

COPY_JS = """
document.addEventListener('click',function(e){
  var el=e.target.closest('.path'); if(!el) return;
  var t=el.dataset.full||el.textContent;
  var done=function(){el.classList.add('copied');
    setTimeout(function(){el.classList.remove('copied')},900)};
  if(navigator.clipboard&&window.isSecureContext){
    navigator.clipboard.writeText(t).then(done)
  } else {
    var ta=document.createElement('textarea');ta.value=t;document.body.appendChild(ta);
    ta.select();try{document.execCommand('copy')}catch(_){}
    document.body.removeChild(ta);done()
  }
});
"""


def esc(s):
    return html.escape(str(s), quote=True)


def url(rel):
    return esc(quote(rel, safe="/"))


def demo_css():
    return "\n".join(d["css"] for d in DEMOS if d["css"])


def section_js():
    return SECTION_JS.replace(
        "COMBAT_STEPS",
        "[" + ",".join("['%s',%d]" % (n, ms) for n, ms in COMBAT_STEPS) + "]")


# --------------------------------------------------------------------------
# frame sequences
# --------------------------------------------------------------------------

FRAME_RE = re.compile(r"^(.*?)[ _-]*(\d{2,})$")


def find_sequences(items, min_frames=3, max_pixels=2_000_000, dir_share=0.6):
    """Spot folders of numbered animation frames.

    `items` is an iterable of (rel_path, width, height). Returns a list of
    dicts sorted by path, each {dir, name, frames, w, h}.

    Numbered filenames are ambiguous -- vendors use them for frames, for tiers,
    and for entirely separate assets -- so three rules have to agree:

    * **Starts at 0 or 1, contiguous.** `jungle_201.png`..`jungle_212.png` are
      twelve different monsters, not a twelve-frame animation.
    * **Small enough to play.** Thirty 2048x8192 sheets numbered 01..30 are a
      monster roster; they also could not be animated in a browser if they were.
    * **Dominates its directory.** `Stat_Attack_01..03` sitting among eighty
      other icons are upgrade tiers. Frames of an animation are what their
      folder is *for*, so the sequences in a directory have to account for most
      of the images in it -- measured collectively, since one folder may
      legitimately hold a walk cycle and an idle cycle side by side.
    """
    per_dir = Counter(posixpath.dirname(rel) for rel, w, h in items if w)
    groups = defaultdict(list)
    for rel, w, h in items:
        if not w or w * h > max_pixels:
            continue
        stem = posixpath.splitext(posixpath.basename(rel))[0]
        m = FRAME_RE.match(stem)
        if not m:
            continue
        base, num = m.group(1), int(m.group(2))
        if not base:
            base = posixpath.basename(posixpath.dirname(rel)) or "frames"
        groups[(posixpath.dirname(rel), base, w, h)].append((num, rel))

    cand = []
    for (d, base, w, h), frames in groups.items():
        if len(frames) < min_frames:
            continue
        frames.sort()
        nums = [n for n, _ in frames]
        if nums[0] > 1 or nums != list(range(nums[0], nums[0] + len(nums))):
            continue
        cand.append({"dir": d, "name": base, "w": w, "h": h,
                     "frames": [r for _, r in frames]})

    covered = Counter()
    for s in cand:
        covered[s["dir"]] += len(s["frames"])
    seqs = [s for s in cand
            if covered[s["dir"]] >= dir_share * per_dir[s["dir"]]]
    seqs.sort(key=lambda s: (s["dir"], s["name"]))
    return seqs


def sequence_fragment(seqs, max_players=8, fps=12):
    """Players for up to `max_players` sequences, spread across the pack."""
    if not seqs:
        return ""
    shown = seqs
    if len(shown) > max_players:
        step = len(shown) / float(max_players)
        shown = [shown[int(i * step)] for i in range(max_players)]

    out = ["<h2>animations <span class=sub>(%d sequences found, showing %d)"
           "</span></h2>" % (len(seqs), len(shown)),
           "<div class=notes><p>These are real frame sequences &mdash; folders "
           "of numbered PNGs that the catalog would otherwise show as dozens of "
           "near-identical cards. Each player holds every frame in the page and "
           "toggles which one is visible, so playback is instant and the frame "
           "rate is yours to set. Vendors rarely ship a timing file, so the "
           "speed here is a guess: 12 fps is a common hand-animation default, "
           "not a value read from the pack.</p></div>",
           "<div class=ugrid>"]
    for s in shown:
        px = " px" if max(s["w"], s["h"]) <= DEMO_MAX_EDGE else ""
        imgs = "".join("<img class='frame%s' src='%s' alt=''>" % (px, url(r))
                       for r in s["frames"])
        # "Attack" alone is ambiguous when four characters each have one, so
        # prefix the subject folder -- the first component below the pack
        parts = s["dir"].split("/")
        title = ("%s &middot; %s" % (esc(parts[1]), esc(s["name"]))
                 if len(parts) > 1 and parts[1] != s["name"] else esc(s["name"]))
        out.append(
            "<div class='ucard fp'>"
            "<div class=hd><b>%s</b><button data-fp=toggle>pause</button></div>"
            "<div class=term>%d frames &middot; %d&times;%d</div>"
            "<div class=stage>%s</div>"
            "<div class=fpctl><button data-step=1>step</button>"
            "<input type=range class=fps min=1 max=30 value=%d>"
            "<span class='val fpsval'>%d fps</span>"
            "<span>frame <b class=fpnum>1/%d</b></span></div>"
            "<div class=path data-full='%s'>%s</div></div>"
            % (title, len(s["frames"]), s["w"], s["h"], imgs,
               fps, fps, len(s["frames"]),
               esc(s["dir"] or "(root)"), esc(s["dir"] or "(root)")))
    out.append("</div>")
    return "".join(out)


# --------------------------------------------------------------------------
# sprite sheets
# --------------------------------------------------------------------------

def detect_grid(path, min_cell=32, max_cols=16, max_rows=64, gutter=0.004):
    """Find the cell grid of a uniform sprite sheet, or None.

    Sheets are laid out on a regular grid with the art inset inside each cell,
    which leaves a fully transparent seam on every cell boundary. So: take the
    square cell sizes that divide both dimensions, and keep the smallest one
    whose boundary columns *and* rows are empty. Smallest matters -- every
    multiple of the true cell size also has empty boundaries, and the finest
    grid is the real one.

    Only the boundary strips are read, never the whole image, so this stays
    cheap on a 2048x8192 sheet.
    """
    try:
        with Image.open(path) as im:
            w, h = im.size
            alpha = im.convert("RGBA").getchannel("A")
    except Exception:
        return None

    def empty(box):
        """Is this strip effectively transparent?"""
        strip = alpha.crop(box)
        n = (box[2] - box[0]) * (box[3] - box[1])
        return n and sum(strip.histogram()[26:]) <= gutter * n

    cells = sorted(c for c in range(min_cell, min(w, h) + 1)
                   if w % c == 0 and h % c == 0
                   and 2 <= w // c <= max_cols and 2 <= h // c <= max_rows)
    for cell in cells:
        cols, rows = w // cell, h // cell
        if not all(empty((x * cell - 1, 0, x * cell + 1, h))
                   for x in range(1, cols)):
            continue
        if not all(empty((0, y * cell - 1, w, y * cell + 1))
                   for y in range(1, rows)):
            continue
        # positive control: the cells themselves must actually hold art
        mid = cell // 2
        if empty((mid - 8, mid - 8, mid + 8, mid + 8)):
            continue
        return cell, cols, rows
    return None


def ensure_sheet_preview(abs_path, rel, out, cols, rows, target=3072):
    """Downscale a sheet for playback and return (rel_path, display_cell).

    A 2048x8192 sheet is ~67 MB decoded. Playing one as a CSS background at
    full size is the difference between a page that opens and one that doesn't,
    and the player only ever shows one cell at a time anyway.
    """
    with Image.open(abs_path) as im:
        w, h = im.size
        scale = min(1.0, target / float(max(w, h)))
        cell_disp = max(24, int(round((w / cols) * scale)))
        size = (cols * cell_disp, rows * cell_disp)
        dst_rel = posixpath.join("_previews", "_sheets",
                                 posixpath.splitext(rel)[0] + ".png")
        dst = os.path.join(out, dst_rel.replace("/", os.sep))
        if (not os.path.exists(dst)
                or os.path.getmtime(dst) < os.path.getmtime(abs_path)):
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            im.convert("RGBA").resize(size, Image.LANCZOS).save(dst)
    return dst_rel, cell_disp


def sheet_fragment(sheets, labels=None, fps=8):
    """Players for detected sprite sheets. `sheets` is a list of dicts from
    build_sheets_data: {rel, src, cols, rows, cell, disp, name}."""
    if not sheets:
        return ""
    out = ["<h2>sprite sheets</h2>",
           "<div class=notes><p>Every animation in this pack is one cell of a "
           "grid inside a single image, which is why the catalog below shows "
           "one card per <i>character</i> rather than per frame. The grid is "
           "detected from the transparent seams between cells, and the player "
           "steps the background position across a row &mdash; exactly what an "
           "engine does.</p>%s</div>"
           % ("<p>%s</p>" % esc(labels["note"]) if labels and labels.get("note")
              else ""),
           "<div class=ugrid>"]
    rowlabels = (labels or {}).get("rows") or []
    for s in sheets:
        opts = "".join(
            "<option value=%d>%s</option>"
            % (i, esc(rowlabels[i] if i < len(rowlabels) else "row %d" % i))
            for i in range(s["rows"]))
        out.append(
            "<div class='ucard sh' data-cols=%d data-rows=%d data-cell=%d>"
            "<div class=hd><b>%s</b><button data-fp=toggle>pause</button></div>"
            "<div class=term>%d&times;%d grid of %dpx cells &middot; %d frames "
            "per row</div>"
            "<div class='stage shstage'><div class=shview style=\"width:%dpx;"
            "height:%dpx;background-image:url('%s')\"></div></div>"
            "<div class=fpctl><select class=shrow>%s</select>"
            "<button data-step=1>step</button>"
            "<input type=range class=fps min=1 max=24 value=%d>"
            "<span class='val fpsval'>%d fps</span>"
            "<span>frame <b class=fpnum>1/%d</b></span></div>"
            "<div class=path data-full='%s'>%s</div></div>"
            % (s["cols"], s["rows"], s["disp"], esc(s["name"]),
               s["cols"], s["rows"], s["cell"], s["cols"],
               s["disp"], s["disp"], s["src"], opts, fps, fps, s["cols"],
               esc(s["rel"]), esc(s["rel"])))
    out.append("</div>")
    return "".join(out)


# --------------------------------------------------------------------------
# single-pose transform demo
# --------------------------------------------------------------------------

def pick_sprite(items, max_edge=DEMO_MAX_EDGE, sample=48):
    """Choose a representative sprite for the transform demo.

    `items` is an iterable of (abs_path, w, h). Small art only -- a sprite sheet
    or a full-size illustration is not what this demonstrates.

    Returns a path, or None if the pack has no suitable art.
    """
    cand = [(p, w, h) for p, w, h in items
            if w and h and max(w, h) <= max_edge]
    if not cand:
        return None

    # Prefer the pack's uniform canvas. Vendors often ship a tight-cropped
    # "min size" copy alongside a padded one; the padded copy is the canonical
    # presentation, and scoring on content alone would always pick the crop.
    modal = Counter((w, h) for _, w, h in cand).most_common(1)[0][0]
    cand = [c for c in cand if (c[1], c[2]) == modal] or cand
    cand.sort(key=lambda t: t[0])

    # cap the work -- scoring every sprite in a 400-file pack is pointless
    if len(cand) > sample:
        step = len(cand) / float(sample)
        cand = [cand[int(i * step)] for i in range(sample)]

    # most actual artwork wins: a sprite that is mostly padding demos nothing
    best, best_score = None, -1
    for path, w, h in cand:
        try:
            with Image.open(path) as im:
                hist = im.convert("RGBA").getchannel("A").histogram()
                score = sum(hist[129:])
        except Exception:
            continue
        if score > best_score:
            best, best_score = path, score
    return best


def fit_scale(h, target, cap=14):
    """Integer scale that brings a sprite of height h to roughly `target` px.
    Big sprites stay at 1x -- upscaling a 512px icon helps nobody."""
    return max(1, min(cap, round(target / float(h)))) if h else 1


def card(d, scale_var):
    """One animation panel: the sprite running it, plus the CSS that runs it.

    Looping animations are applied at render time. One-shots are not -- a death
    animation ending at opacity 0 would just look like a missing image on load.
    """
    btn = ("<button data-play='%s'>play</button>" % esc(d["id"])
           if d.get("trigger") else "")
    cls = "" if d["id"] == "static" or d.get("trigger") else " a-" + d["id"]
    hold = " data-trigger=1" if d.get("trigger") else ""
    src = ("<pre>%s</pre>" % esc(d["css"])) if d["css"] else \
          "<pre>/* no animation -- the file as shipped */</pre>"
    return ("<div class=ucard style='--cardscale:%s'>"
            "<div class=hd><b>%s</b>%s</div>"
            "<div class=term>%s</div>"
            "<div class=stage><img class='sprite%s' data-anim='%s'%s "
            "src='SPRITE_SRC' alt=''></div>"
            "<p class=why>%s</p>%s</div>"
            % (scale_var, esc(d["label"]), btn, esc(d.get("term", "")),
               cls, esc(d["id"]), hold, esc(d["note"]), src))


def transform_fragment(rel, w, h, bbox=None):
    """The single-pose demo, as HTML to drop inside a `.usage` container.

    `rel` is the sprite's path relative to the page that will hold it.
    """
    src = url(rel)
    card_scale = fit_scale(h, 120)
    hero_scale = fit_scale(h, 190)

    content_note = ""
    if bbox:
        cw, ch = bbox[2] - bbox[0], bbox[3] - bbox[1]
        if (cw, ch) != (w, h):
            content_note = (" &middot; artwork occupies %d&times;%d of that canvas"
                            % (cw, ch))

    body = [
        "<h2>how a single frame moves</h2>",
        "<div class=notes><p>A pack with one pose per creature is not missing "
        "its animation &mdash; it has a different animation budget. Everything "
        "below moves the sprite without redrawing it: CSS transforms, a filter, "
        "and opacity. A game engine does exactly the same thing with the same "
        "maths, which is why an icon set can populate a battle screen.</p>"
        "<p>Every panel is <b>",
        esc(os.path.basename(rel)), "</b> &mdash; %d&times;%d source pixels%s "
        "&mdash; unmodified. The CSS under each panel is the CSS running in it."
        "</p><p><span class=path data-full='%s'>%s</span></p></div>"
        % (w, h, content_note, esc(rel), esc(rel)),

        "<div class=controls>"
        "<label>scale <input type=range id=sc min=1 max=14 step=.25 value=%d>"
        "<span class=val id=scval>%dx</span></label>"
        "<label><input type=checkbox id=snap checked> integer scale only</label>"
        "<label><input type=checkbox id=sm> smooth filtering</label>"
        "</div>" % (hero_scale, hero_scale),

        "<p class=warn id=nonint hidden>&#9888; Non-integer scale: some source "
        "pixels are now wider than their neighbours. In motion this shimmers, "
        "which is why pixel-art games scale the whole framebuffer by a whole "
        "number instead of scaling sprites freely.</p>",
        "<p class=warn>Turn on smooth filtering to see the other half of it. "
        "That is bilinear &mdash; the browser default, and Unity's default "
        "import setting. Pixel-art packs commonly ship "
        "<code>filterMode: 0</code> (Point) precisely to avoid it.</p>",

        "<div class=side><div class=ucard style='--cardscale:var(--scale)'>"
        "<div class=hd><b>live</b></div>"
        "<div class=stage style='height:260px'>"
        "<img class=sprite src='SPRITE_SRC' alt=''></div></div>"
        "<div class=ucard style='--cardscale:1'>"
        "<div class=hd><b>1:1, actual size</b></div>"
        "<div class=stage style='height:260px'>"
        "<img class=sprite src='SPRITE_SRC' alt=''></div>"
        "<p class=why>What the file really is. At 1080p this is about 3% of "
        "screen height.</p></div></div>",

        "<h3 class=sub style='margin:26px 0 6px'>motion from transforms alone"
        "</h3>",
        "<div class=notes><p>The line under each title is the term other people "
        "use. Some are genuinely standard &mdash; <b>squash and stretch</b>, "
        "<b>anticipation</b> and <b>follow-through</b> are three of the twelve "
        "principles of animation, and <b>hitstun</b>, <b>knockback</b>, "
        "<b>easing</b> and <b>tweening</b> are all real terms of art. Others, "
        "like &ldquo;bob&rdquo; and &ldquo;fake walk&rdquo;, are just "
        "descriptions; there is no accepted name for them.</p>"
        "<p>The umbrella terms worth searching are <b>procedural animation</b> "
        "(moving art you did not redraw) and <b>game feel</b> or <b>juice</b> "
        "(the whole business of making input and impact feel physical). Steve "
        "Swink's <i>Game Feel</i> and Jan Willem Nijman's <i>The Art of "
        "Screenshake</i> are the usual starting points.</p></div>",
        "<div class=ugrid>",
    ]
    for d in DEMOS:
        body.append(card(d, card_scale))
    body.append("</div>")

    body.append(
        "<h3 class=sub style='margin:26px 0 6px'>assembled</h3>"
        "<div class=ucard style='--cardscale:" + str(fit_scale(h, 150)) +
        ";max-width:420px'>"
        "<div class=hd><b>combat loop &mdash; <span id=looplbl "
        "style='color:var(--accent)'>stopped</span></b>"
        "<button id=loopbtn>start</button></div>"
        "<div class=stage style='height:230px'>"
        "<img class=sprite id=loopsprite src='SPRITE_SRC' alt=''></div>"
        "<p class=why>idle &rarr; lunge &rarr; idle &rarr; take a hit &rarr; "
        "idle. Four states, one image, no frame budget at all.</p></div>")

    body.append(
        "<div class=notes style='margin-top:22px'><p><b>Where you have seen "
        "this.</b> It is the JRPG battle screen. In the NES-era Final Fantasy "
        "games the enemies are single static images &mdash; the whole attack "
        "readout is the party member stepping forward, the enemy flashing, and "
        "a damage number. The hit flash is the oldest piece here and survived "
        "because it was nearly free: on that hardware it was a palette swap "
        "rather than a filter. The idle bob is <i>not</i> the old part; those "
        "enemies sit perfectly still, and constant subtle motion is a later "
        "mobile and idle-game habit. It is common again now for a different "
        "reason &mdash; it lets a small team ship ninety-six enemies instead "
        "of twelve. Slay the Spire is the usual modern example.</p>"
        "<p><b>What it does not get you.</b> Transform animation cannot change "
        "silhouette. A creature that should open its wings, swing a weapon it "
        "is holding, or turn to face another direction needs real frames. It "
        "also has to be a whole-project decision: a hand-animated player "
        "character next to a bobbing static monster reads as unfinished.</p>"
        "</div>")

    return "".join(body).replace("SPRITE_SRC", src)


# --------------------------------------------------------------------------
# standalone page
# --------------------------------------------------------------------------

def build(sprite_abs, out_dir, back=None):
    with Image.open(sprite_abs) as im:
        w, h = im.size
        bbox = im.convert("RGBA").getbbox()
    rel = os.path.relpath(sprite_abs, out_dir).replace(os.sep, "/")
    name = os.path.basename(sprite_abs)

    head = ["<header><h1>Sprite motion &mdash; ", esc(name), "</h1>"]
    if back:
        head.append("<div class=sub><a href='%s'>&larr; back to the catalog "
                    "index</a></div>" % url(back))
    head.append("</header><main class=usage style='--w:%d'>" % w)

    return (MARKER + "<!doctype html><html lang=en><meta charset=utf-8>"
            "<meta name=viewport content='width=device-width,initial-scale=1'>"
            "<title>Sprite motion &mdash; " + esc(name) + "</title>"
            "<style>" + PAGE_CHROME + SECTION_CSS + demo_css() + "</style><body>"
            + "".join(head)
            + transform_fragment(rel, w, h, bbox)
            + "</main><script>" + section_js() + COPY_JS + "</script></html>")


def main():
    ap = argparse.ArgumentParser(
        description="Demo page showing a static sprite animated by transforms only.")
    ap.add_argument("sprite", help="path to one PNG")
    ap.add_argument("--out", help="directory to write %s into "
                                  "(default: the sprite's directory)" % PAGE_NAME)
    ap.add_argument("--index", default="index.html", metavar="PAGE",
                    help="catalog page to link back to, relative to --out "
                         "(default index.html; '' for no link)")
    args = ap.parse_args()

    sprite = os.path.abspath(args.sprite)
    if not os.path.isfile(sprite):
        sys.exit("no such file: %s" % sprite)
    out = os.path.abspath(args.out) if args.out else os.path.dirname(sprite)
    os.makedirs(out, exist_ok=True)

    # linked unconditionally rather than only when the file is already there --
    # an existence check would make the generated page depend on which order
    # this and catalog.py happened to run in
    back = args.index or None

    with Image.open(sprite) as im:
        sw, sh = im.size
    if max(sw, sh) > 512:
        print("note: %dx%d is large for this page -- it demonstrates how a small "
              "single-frame sprite is animated, and a sheet or full-size artwork "
              "will just be letterboxed." % (sw, sh), file=sys.stderr)

    dst = os.path.join(out, PAGE_NAME)
    with open(dst, "w", encoding="utf-8") as fh:
        fh.write(build(sprite, out, back))
    print("motion demo -> %s" % dst)


if __name__ == "__main__":
    main()
